# action.yml
name: 'Build Dockerfile'
description: 'A simple dockerfile build action'
inputs: 
    docker-build-args:
    description: 'docker build-args arguments'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker-build-args }}
