on:
  push:
jobs:
  sprout_data_exchange_job:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run build-tools build command
        env: # environment variables
          APTIBLE_USER: ${{ secrets.APTIBLE_USER }}
          APTIBLE_PASSWORD: ${{ secrets.APTIBLE_PASSWORD }}
        uses: buildtool/build-action@v1
        with:
          dockerfile: dockerfiles/Dockerfile
          docker-build-args: '--build-arg "APTIBLE_USER=${APTIBLE_USER}" --build-arg "APTIBLE_PASSWORD=${APTIBLE_PASSWORD}"'
