on: [push]

jobs:
  sprout_data_exchange_job:
    runs-on: ubuntu-latest
    name: A job to build a dcyf-cssat exchange 
    steps:
      # check out the repository (required for private repos/actions)
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the container
        uses: ./ # Uses an action in the root directory
        id: build
        env: # Or as an environment variable
          APTIBLE_USER: ${{ secrets.APTIBLE_USER }}
          APTIBLE_PASSWORD: ${{ secrets.APTIBLE_PASSWORD }}
        docker-build-args: '--build-arg "APTIBLE_USER=${APTIBLE_USER}" --build-arg "APTIBLE_PASSWORD=${APTIBLE_PASSWORD}"'
      # print a completion message
      - name: Get the output time
        run: echo "The completion time was ${{ steps.build.outputs.time }}"
