on:
  push:

jobs:
  sprout_data_exchange_job:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run build with args
        uses: joemienko/sprout-data-exchange@v1.0
        env: # environment variables
          APTIBLE_USER: ${{ secrets.APTIBLE_USER }}
          APTIBLE_PASSWORD: ${{ secrets.APTIBLE_PASSWORD }}
        with:
          docker-build-args: '--build-arg "APTIBLE_USER=${APTIBLE_USER}" --build-arg "APTIBLE_PASSWORD=${APTIBLE_PASSWORD}"'
